Repository DuncteBot/SkyBot, pull requests merged in 2018-09, with the labels that each got.

#49 Rewrite patron checker
  .idea/sqldialects.xml
  src/main/java/ml/duncte123/skybot/BotListener.java
  src/main/java/ml/duncte123/skybot/connections/database/MySQLConnectionManager.java
  src/main/java/ml/duncte123/skybot/connections/database/SQLiteDatabaseConnectionManager.java
  src/main/java/ml/duncte123/skybot/objects/command/Command.java
  src/main/java/ml/duncte123/skybot/utils/GuildSettingsUtils.java
  src/main/resources/public/css/materialize.custom.css
  src/main/resources/views/templates/base.twig
Labels: enhancement

#50 Manual Event Repeating & Minor Fixes
  src/main/java/ml/duncte123/skybot/BotListener.java
  src/main/java/ml/duncte123/skybot/SkyBot.java
  src/main/java/ml/duncte123/skybot/connections/database/MySQLConnectionManager.java
  src/main/java/ml/duncte123/skybot/objects/command/Command.java
  src/main/java/ml/duncte123/skybot/objects/config/DunctebotConfig.java
  src/main/kotlin/ml/duncte123/skybot/Emojis.kt
  src/main/kotlin/ml/duncte123/skybot/ReactionHandler.kt
  src/main/kotlin/ml/duncte123/skybot/commands/essentials/eval/EvalCommand.kt
  src/main/kotlin/ml/duncte123/skybot/objects/EvalFunctions.kt
Labels: bug, enhancement, kotlin

#52 Make search command listen for chat events
  src/main/java/ml/duncte123/skybot/BotListener.java
  src/main/java/ml/duncte123/skybot/EventManager.java
  src/main/java/ml/duncte123/skybot/SkyBot.java
  src/main/java/ml/duncte123/skybot/objects/command/CommandContext.java
  src/main/java/ml/duncte123/skybot/utils/AirUtils.java
  src/main/java/ml/duncte123/skybot/utils/MessageUtils.java
  src/main/kotlin/ml/duncte123/skybot/ReactionCacheElement.kt
  src/main/kotlin/ml/duncte123/skybot/ReactionHandler.kt
  src/main/kotlin/ml/duncte123/skybot/commands/music/SearchCommand.kt
Labels: enhancement

#65 Add ban't alias for unban
  src/main/java/ml/duncte123/skybot/commands/guild/mod/UnbanCommand.java
Labels: enhancement

#63 Store the changelog embed as json
  src/main/java/ml/duncte123/skybot/commands/guild/owner/CustomCommandCommand.java
  src/main/java/ml/duncte123/skybot/commands/uncategorized/ChangeLogCommand.java
Labels: enhancement

#67 Block commands marked as NSFW in none NSFW channels
  src/main/java/ml/duncte123/skybot/CommandManager.java
  src/main/java/ml/duncte123/skybot/commands/fun/UrbanCommand.java
Labels: bug

#78 [BUG] devs can't use db!forceleave
  build.gradle
  src/main/java/ml/duncte123/skybot/commands/guild/owner/ForceDisconnectCommand.java
  src/main/kotlin/ml/duncte123/skybot/Annotations.kt
  src/main/kotlin/ml/duncte123/skybot/commands/essentials/RestartShardCommand.kt
  src/main/kotlin/ml/duncte123/skybot/commands/essentials/UpdateCommand.kt
  src/main/kotlin/ml/duncte123/skybot/commands/essentials/eval/EvalCommand.kt
  src/main/kotlin/ml/duncte123/skybot/commands/music/RepeatCommand.kt
Labels: bug

#74 Lavalink region balancing
  build.gradle
  src/main/java/fredboat/audio/player/LavalinkManager.java
  src/main/java/ml/duncte123/skybot/SkyBot.java
  src/main/java/ml/duncte123/skybot/objects/config/DunctebotConfig.java
Labels: enhancement
