Repository DuncteBot/SkyBot, pull requests merged in 2018-10, with the labels that each got.

#80 Update jda
  build.gradle
  src/main/java/ml/duncte123/skybot/EventManager.java
  src/main/java/ml/duncte123/skybot/SkyBot.java
  src/main/java/ml/duncte123/skybot/objects/command/CommandContext.java
Labels: enhancement, hacktoberfest

#82 Add pretty time
  build.gradle
  src/main/kotlin/ml/duncte123/skybot/commands/uncategorized/UserinfoCommand.kt
Labels: enhancement, hacktoberfest

#85 Add shard_count to api
  src/main/kotlin/ml/duncte123/skybot/web/WebServer.kt
Labels: enhancement

#94 Handle blocked videos
  src/main/java/ml/duncte123/skybot/utils/AudioUtils.java
Labels: hacktoberfest

#109 Use finder utils to clean code
  build.gradle
  src/main/java/ml/duncte123/skybot/utils/AirUtils.java
  src/main/kotlin/ml/duncte123/skybot/commands/uncategorized/UserinfoCommand.kt
Labels: enhancement

#111 Increasing custom command name length
  src/main/java/ml/duncte123/skybot/commands/guild/owner/CustomCommandCommand.java
  src/main/java/ml/duncte123/skybot/connections/database/MySQLConnectionManager.java
  src/main/java/ml/duncte123/skybot/connections/database/SQLiteDatabaseConnectionManager.java
Labels: hacktoberfest

#114 Update all libraries
  build.gradle
  src/main/java/ml/duncte123/skybot/objects/audiomanagers/spotify/SpotifyAudioSourceManager.java
  src/main/java/spark/template/jtwig/JtwigTemplateEngine.java
  src/main/kotlin/ml/duncte123/skybot/web/WebServer.kt
Labels: completed

#116 Update botfarm filter
  src/main/java/ml/duncte123/skybot/BotListener.java
  src/main/java/ml/duncte123/skybot/utils/GuildUtils.java
Labels: completed, enhancement

#117 [BUG FIX] Fix spotify playlist loading
  src/main/java/ml/duncte123/skybot/objects/audiomanagers/spotify/SpotifyAudioSourceManager.java
Labels: bug, completed

#118 Fix lyrics command
  build.gradle
  src/main/kotlin/ml/duncte123/skybot/commands/music/LyricsCommand.kt
Labels: bug, completed

#119 Update kotlin
  build.gradle
  src/main/java/ml/duncte123/skybot/commands/essentials/ShardInfoCommand.java
  src/main/kotlin/ml/duncte123/skybot/ReactionCacheElement.kt
  src/main/kotlin/ml/duncte123/skybot/commands/essentials/RestartShardCommand.kt
  src/main/kotlin/ml/duncte123/skybot/commands/essentials/StatsCommand.kt
  src/main/kotlin/ml/duncte123/skybot/commands/essentials/UpdateCommand.kt
  src/main/kotlin/ml/duncte123/skybot/commands/essentials/eval/EvalCommand.kt
  src/main/kotlin/ml/duncte123/skybot/commands/music/LyricsCommand.kt
Labels: completed, enhancement
